@startuml
left to right direction
' class QObject
class main
!include class/IGame.iuml
'IGame ..|> QObject
!include class/TempleRunner.iuml
!include class/SomeOtherGame.iuml

TempleRunner ..|> IGame
SomeOtherGame ..|> IGame

!include class/IArduino.iuml

'IArduino ..|> QObject

IArduino <-- main
IGame "3"<--"1" main
WheelWidget <-- main
!include class/ArduinoSerial.iuml

!include class/FakeWheel.iuml

ArduinoSerial ..|> IArduino
FakeWheel ..|> IArduino

!include class/WheelWidget.iuml

'WheelWidget ..|> QWidget
@enduml
