@startuml
left to right direction
' class QObject
class main
abstract IGame {
    --signals--
    + setLED()
    + setResistance()
    --slots--
    + {abstract} update(speed: int, weight: int, gameIdx: int, reset: bool)
    + {abstract} start()
}
'IGame ..|> QObject

class TempleRunner {
    --slots--
    + start()
    + update(speed: int, weight: int, gameIdx: int, reset: bool)
}

class SomeOtherGame{
    --slots--
    + start()
    + update(speed: int, weight: int, gameIdx: int, reset: bool)
}

TempleRunner ..|> IGame
SomeOtherGame ..|> IGame

abstract IArduino {
    --slots--
    + {abstract} setLED(index: int, r: int, g: int, b: int)
    + {abstract} setResistance(int)
    --signals--
    + onData(speed: int, weight: int, gameIdx: int, reset: bool)
}

'IArduino ..|> QObject

IArduino <-- main
IGame "3"<--"1" main
WheelWidget <-- main
class ArduinoSerial {
    --slots--
    + setLED(index: int, r: int, g: int, b: int)
    + setResistance(int)
}

class FakeWheel {
    --slots--
    + setLED(index: int, r: int, g: int, b: int)
    + setResistance(int)
}
ArduinoSerial ..|> IArduino
FakeWheel ..|> IArduino

class WheelWidget {
    + rpmGauge(): Gauge*
    + weightGauge(): Gauge*
}

'WheelWidget ..|> QWidget
@enduml
