@startuml
left to right direction
skinparam dpi 400

class main
!include class/IGame.iuml

!include class/TempleRunner.iuml
!include class/SomeOtherGame.iuml

TempleRunner ..|> IGame
SomeOtherGame ..|> IGame

!include class/IArduino.iuml

!include class/ArduinoSerial.iuml

ArduinoSerial ..|> IArduino

!include class/WheelWidget.iuml

IArduino "1" o-left- main
IGame "3" o-right- main
WheelWidget "1" o-down- main
@enduml
