#ifndef TEMPLERUNNER_GLOBAL_H
#define TEMPLERUNNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPLERUNNER_LIBRARY)
#  define TEMPLERUNNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPLERUNNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPLERUNNER_GLOBAL_H
